from enum import IntEnum


class DOTAUnitTargetTeam(IntEnum):
    DOTA_UNIT_TARGET_TEAM_NONE = 0
    DOTA_UNIT_TARGET_TEAM_FRIENDLY = 1
    DOTA_UNIT_TARGET_TEAM_ENEMY = 2
    DOTA_UNIT_TARGET_TEAM_BOTH = 3
    DOTA_UNIT_TARGET_TEAM_CUSTOM = 4
